spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_boot_scaffold?serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  error:
    include-stacktrace: never
  port: 8888