spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_example?serverTimezone=UTC
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  error:
    include-stacktrace: never
  port: 8888

casbin:
  storeType: jdbc
  model: classpath:model.conf

springfox:
  documentation:
    swaggerUi:
      baseUrl: /docs # /docs/swagger-ui/index.html
    openApi:
      v3:
        path: /docs/v3/api-docs
